# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{wkhtmltopdf_for_rails}
  s.version = "0.0.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Alexey Osipenko"]
  s.date = %q{2010-04-29}
  s.description = %q{Provides WKHTMLTOPDF for ruby on rails.}
  s.email = %q{alexey@osipenko.in.ua}
  s.executables = ["wkhtmltopdf", "wkhtmltopdf-amd64", "wkhtmltopdf-binary.rb", "wkhtmltopdf_darwin_386", "wkhtmltopdf_linux_386", "wkhtmltopdf"]
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    ".gitignore",
     "Manifest",
     "README",
     "VERSION",
     "bin/wkhtmltopdf",
     "bin/wkhtmltopdf-amd64",
     "bin/wkhtmltopdf-binary.rb",
     "bin/wkhtmltopdf_darwin_386",
     "bin/wkhtmltopdf_linux_386",
     "init.rb",
     "lib/render_pdf.rb",
     "lib/wkhtmltopdf.rb",
     "lib/wkhtmltopdf_for_rails.rb",
     "rakefile",
     "test/fixtures/wkhtmltopdf.html",
     "test/pdfs/.gitignore",
     "test/test_helper.rb",
     "test/tmp/.gitkeep",
     "test/wkhtmltopdf_test.rb",
     "test/wkhtmltopdf_test_controller_test.rb"
  ]
  s.homepage = %q{http://github.com/aratak/wkhtmltopdf_for_rails}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Provides WKHTMLTOPDF for ruby on rails.}
  s.test_files = [
    "test/test_helper.rb",
     "test/wkhtmltopdf_test.rb",
     "test/wkhtmltopdf_test_controller_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

